# Generated by Django 4.1.3 on 2022-11-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upi_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_form',
            name='mobile_number',
            field=models.CharField(max_length=15),
        ),
    ]
